name: Import ReqIF to GitHub

on:
  push:
    paths:
      - '**/*.reqif'        # Triggers for any .reqif file update
  workflow_dispatch:         # Allows manual run from GitHub UI

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (Full Clone)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensures all files are checked out

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # --- Consolidate steps and use 'working-directory' ---
    - name: Install dependencies and Run import script
      # CRITICAL FIX: Set the working directory to the subdirectory.
      working-directory: SysReqImport
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # Files are now relative to SysReqImport, so use the local filename only.
        REQIF_FILE: requirements.reqif 
        
      run: |
        echo "Contents of working directory ($PWD):"
        ls -la
        
        # 1. Install dependencies (now runs inside SysReqImport)
        echo "Installing dependencies..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        # 2. Run the import script (now runs inside SysReqImport)
        echo "Running import script..."
        python import_reqif_to_github.py