name: Import ReqIF to GitHub

on:
  push:
    paths:
      - '**/*.reqif' # triggers when any .reqif file is added, changed, or edited
  workflow_dispatch: # allows manual run from GitHub UI

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (Full Clone)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensures all files are checked out

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # --- Step 1: Install dependencies using working-directory ---
    - name: Install dependencies
      # Set the working directory to the root, where requirements.txt is located.
      working-directory: ${{ github.workspace }}
      run: |
        echo "Installing dependencies from $(pwd)..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # --- Step 2: Run the script using working-directory ---
    - name: Run import script
      # Set the working directory to the root, where the script is located.
      working-directory: ${{ github.workspace }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # The REQIF_FILE environment variable needs the full path from the root.
        REQIF_FILE: requirements.reqif
        
      run: |
        echo "Running script from $(pwd)..."
        # The Python script uses the environment variable REQIF_FILE, 
        # which is set above to 'requirements.reqif' and is found in this directory.
        python import_reqif_to_github.py