name: Import ReqIF to GitHub

on:
  push:
    # Trigger on change to requirements.reqif file at the root
    paths:
      - 'requirements.reqif' 
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Single step to install dependencies and run the script from the root.
    - name: Install dependencies and Run import script
      
      # NOTE: working-directory is OMITTED because all files are at the root.
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # The file path is simply the local filename at the root.
        REQIF_FILE: requirements.reqif 
        
      run: |
        echo "Starting execution in CWD: $(pwd)"
        
        # 1. Install dependencies (requirements.txt is found at the root)
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        # 2. Run the import script (import_reqif_to_github.py is found at the root)
        python import_reqif_to_github.py