name: Import ReqIF to GitHub

on:
  push:
    paths:
      - '**/*.reqif'
  workflow_dispatch:

# 🔑 CRITICAL FIX: Add this permissions block
permissions:
  contents: read  # Allow the checkout action to read the code
  issues: write   # Allow the script to create issues

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (Full Clone)
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies and Run import script
      working-directory: SysReqImport
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        REQIF_FILE: requirements.reqif
        
      run: |
        echo "Contents of working directory ($PWD):"
        ls -la
        
        # 1. Install dependencies
        echo "Installing dependencies..."
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        # 2. Run the import script
        echo "Running import script..."
        python import_reqif_to_github.py