name: Import ReqIF to GitHub

on:
  push:
    paths:
      - '**/*.reqif'        # triggers when any .reqif file is added, changed, or edited
  workflow_dispatch:         # allows manual run from GitHub UI

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (Full Clone)
      uses: actions/checkout@v4
      with:
        # Full clone ensures all recent file changes are retrieved
        fetch-depth: 0 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies and Run import script
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        # Set REQIF_FILE to the local filename only, since it is at the root.
        REQIF_FILE: requirements.reqif 
        
      run: |
        echo "Starting execution in CWD: $(pwd)"
        
        # FINAL DEBUG: Confirm files are now visible at the root
        echo "Contents of working directory:"
        ls -la
        echo "==================================================="

        # 1. Install dependencies (all files are at the root)
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        # 2. Run the import script (script is at the root)
        python import_reqif_to_github.py