name: Import ReqIF to GitHub

on:
  push:
    paths:
      - 'requirements.reqif' 
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository (Full Clone)
      uses: actions/checkout@v4
      with:
        #  Critical Fix: Fetch full history to ensure all files are present.
        fetch-depth: 0 

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies and Run import script
      
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        REQIF_FILE: requirements.reqif 
        
      run: |
        echo "Starting execution in CWD: $(pwd)"
        
        # DEBUG: Re-check contents to confirm files are here now.
        echo "Contents of working directory after full clone:"
        ls -la
        echo "==================================================="

        # 1. Install dependencies
        python -m pip install --upgrade pip
        pip install -r requirements.txt

        # 2. Run the import script
        python import_reqif_to_github.py